In [78]:
import numpy as np 
import pandas as pd 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder , StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix

file = r"C:\Users\KOIN\Downloads\jaipur_house_prices.csv"

df = pd.read_csv(file)
df.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move
1,16,Rajasthan,Jaipur,Locality_369,Apartment,1,2815,491.97,0.17,2015,...,10,9,6,High,Yes,Yes,Playground,East,Owner,Under_Construction
2,24,Rajasthan,Jaipur,Locality_355,Independent House,4,3176,164.31,0.05,1990,...,35,9,4,Low,Yes,No,"Pool, Gym, Clubhouse",East,Builder,Under_Construction
3,61,Rajasthan,Jaipur,Locality_40,Apartment,3,4253,92.82,0.02,1990,...,35,2,4,Medium,Yes,No,"Gym, Clubhouse, Playground, Pool, Garden",West,Builder,Under_Construction
4,82,Rajasthan,Jaipur,Locality_63,Villa,3,4649,176.55,0.04,1996,...,29,8,4,High,No,No,"Garden, Gym, Clubhouse",East,Owner,Ready_to_Move

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6231 entries, 0 to 6230
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID                              6231 non-null   int64
 1   State                           6231 non-null   object
 2   City                            6231 non-null   object
 3   Locality                        6231 non-null   object
 4   Property_Type                   6231 non-null   object
 5   BHK                             6231 non-null   int64
 6   Size_in_SqFt                    6231 non-null   int64
 7   Price_in_Lakhs                  6231 non-null   float64
 8   Price_per_SqFt                  6231 non-null   float64
 9   Year_Built                      6231 non-null   int64
 10  Furnished_Status                6231 non-null   object
 11  Floor_No                        6231 non-null   int64
 12  Total_Floors                    6231 non-null   int64
 13  Age_of_Property                 6231 non-null   int64
 14  Nearby_Schools                  6231 non-null   int64
 15  Nearby_Hospitals                6231 non-null   int64
 16  Public_Transport_Accessibility  6231 non-null   object
 17  Parking_Space                   6231 non-null   object
 18  Security                        6231 non-null   object
 19  Amenities                       6231 non-null   object
 20  Facing                          6231 non-null   object
 21  Owner_Type                      6231 non-null   object
 22  Availability_Status             6231 non-null   object
dtypes: float64(2), int64(9), object(12)
memory usage: 1.1+ MB

In [80]:
df.columns

Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='object')

In [81]:
df.describe()

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals
count,6231.000000,6231.000000,6231.000000,6231.000000,6231.000000,6231.000000,6231.000000,6231.000000,6231.000000,6231.000000,6231.000000
mean,124513.156155,3.002086,2768.259669,255.246241,0.129286,2006.579522,15.240892,15.770502,18.420478,5.525116,5.515166
std,72210.162483,1.408469,1292.987482,141.551291,0.130774,9.793308,9.056568,8.655710,9.793308,2.893337,2.898893
min,5.000000,1.000000,501.000000,10.020000,0.000000,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000
25%,62382.500000,2.000000,1663.000000,135.275000,0.050000,1998.000000,7.000000,8.000000,10.000000,3.000000,3.000000
50%,124136.000000,3.000000,2776.000000,251.630000,0.090000,2007.000000,15.000000,16.000000,18.000000,6.000000,6.000000
75%,186006.500000,4.000000,3881.000000,381.525000,0.160000,2015.000000,23.000000,23.000000,27.000000,8.000000,8.000000
max,249980.000000,5.000000,5000.000000,499.980000,0.990000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000

In [82]:
df.isnull().sum()

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [83]:

df.fillna(df.mean(numeric_only=True), inplace=True)
df.isnull().sum()

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [84]:
df.columns

Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='object')

In [89]:
l = LabelEncoder()
df["ID"]=l.fit_transform(df["ID"])

x= df.drop("ID", axis=1)
y= df["ID"]

In [90]:
binary = ["Parking_Space" , "Security"]
numeric = ["Size_in_SqFt", "Price_in_Lakhs", "Price_per_SqFt"]

In [92]:
preprocessing_data  = ColumnTransformer (
    transformers = [
        ("cat", OneHotEncoder(drop="first") , binary)
        ,
        ("num" , StandardScaler() , numeric)
    ]
)

In [94]:
x_train ,x_test, y_train, y_test = train_test_split(x,y, test_size=0.3 , random_state=45)

In [97]:
model.fit(x_train, y_train )

Pipeline(steps=[('preprocessing ',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['Parking_Space',
                                                   'Security']),
                                                 ('num', StandardScaler(),
                                                  ['Size_in_SqFt',
                                                   'Price_in_Lakhs',
                                                   'Price_per_SqFt'])])),
                ('classifire', LogisticRegression())])

In [96]:
model = Pipeline(steps=[
    ("preprocessing " , preprocessing_data)
    ,
    ("classifire" , LogisticRegression())
])

In [99]:
y_pred = model.predict(x_test)

print(accuracy_score , (y_test,y_pred))

print(confusion_matrix, (y_test, y_pred))

<function accuracy_score at 0x000002126ED9F600> (210      210
2411    2411
5457    5457
5086    5086
4069    4069
        ...
5062    5062
2488    2488
4328    4328
221      221
2299    2299
Name: ID, Length: 1870, dtype: int64, array([3826, 5325, 1496, ..., 6226, 2403, 2053]))
<function confusion_matrix at 0x000002126ED9F740> (210      210
2411    2411
5457    5457
5086    5086
4069    4069
        ...
5062    5062
2488    2488
4328    4328
221      221
2299    2299
Name: ID, Length: 1870, dtype: int64, array([3826, 5325, 1496, ..., 6226, 2403, 2053]))