In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\koin\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\koin\appdata\roaming\python\python313\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\koin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\koin\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\koin\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\koin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\koin\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.4.0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.16.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 1.8 MB/s eta 0:00:05
   ----- ---------------------------------- 1.0/8.0 MB 1.5 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.0 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.0 MB 1.4 MB/s eta 0:00:05
   --------- ------------------------------ 1.8/8.0 MB 1.4 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.0 MB 1.4 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.0 MB 1.4 MB/s eta 0:00:04
   ------------- -------------------------- 2.6/8.0 MB 1.4 MB/s eta 0:00:04
   -------------- ------------------------- 2.9/8.0 MB 1.3 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.0 MB 1.3 MB/s eta 0:00:04
   ----------------- ---------------------- 3.4/8.0 MB 1.3 MB/s eta 0:00:04
   ------------------ --------------------- 3.7/8.0 MB 1.3 MB/s eta 0:00:04
   ------------------ --------------------- 3.7/8.0 MB 1.3 MB/s eta 0:00:04
   ------------------- -------------------- 3.9/8.0 MB 1.3 MB/s eta 0:00:04
   -------------------- ------------------- 4.2/8.0 MB 1.2 MB/s eta 0:00:04
   -------------------- ------------------- 4.2/8.0 MB 1.2 MB/s eta 0:00:04
   ---------------------- ----------------- 4.5/8.0 MB 1.2 MB/s eta 0:00:03
   ---------------------- ----------------- 4.5/8.0 MB 1.2 MB/s eta 0:00:03
   ----------------------- ---------------- 4.7/8.0 MB 1.1 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.0 MB 1.1 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.0 MB 1.1 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.0 MB 1.1 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.0 MB 1.1 MB/s eta 0:00:03
   -------------------------- ------------- 5.2/8.0 MB 967.3 kB/s eta 0:00:03
   -------------------------- ------------- 5.2/8.0 MB 967.3 kB/s eta 0:00:03
   -------------------------- ------------- 5.2/8.0 MB 967.3 kB/s eta 0:00:03
   --------------------------- ------------ 5.5/8.0 MB 925.5 kB/s eta 0:00:03
   --------------------------- ------------ 5.5/8.0 MB 925.5 kB/s eta 0:00:03
   --------------------------- ------------ 5.5/8.0 MB 925.5 kB/s eta 0:00:03
   --------------------------- ------------ 5.5/8.0 MB 925.5 kB/s eta 0:00:03
   --------------------------- ------------ 5.5/8.0 MB 925.5 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.0 MB 812.7 kB/s eta 0:00:03
   ------------------------------ --------- 6.0/8.0 MB 693.9 kB/s eta 0:00:03
   ------------------------------ --------- 6.0/8.0 MB 693.9 kB/s eta 0:00:03
   ------------------------------ --------- 6.0/8.0 MB 693.9 kB/s eta 0:00:03
   ------------------------------ --------- 6.0/8.0 MB 693.9 kB/s eta 0:00:03
   ------------------------------ --------- 6.0/8.0 MB 693.9 kB/s eta 0:00:03
   ------------------------------ --------- 6.0/8.0 MB 693.9 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.0 MB 621.0 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.0 MB 621.0 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.0 MB 621.0 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.0 MB 621.0 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.0 MB 621.0 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.0 MB 583.8 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.0 MB 583.8 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.0 MB 583.8 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.0 MB 583.8 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.0 MB 583.8 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 557.0 kB/s eta 0:00:03
   ----------------------------------- ---- 7.1/8.0 MB 509.4 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.0 MB 509.4 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.0 MB 509.4 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.0 MB 509.4 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.0 MB 509.4 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.0 MB 509.4 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.0 MB 509.4 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 473.6 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 473.6 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 473.6 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 473.6 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 473.6 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 473.6 kB/s eta 0:00:02
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 453.6 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 361.6 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 361.6 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 361.6 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 361.6 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 361.6 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 361.6 kB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 346.6 kB/s  0:00:22
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.16.3-cp313-cp313-win_amd64.whl (38.5 MB)
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.5/38.5 MB 104.3 kB/s eta 0:06:05
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
    --------------------------------------- 0.8/38.5 MB 78.5 kB/s eta 0:08:01
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.0/38.5 MB 78.2 kB/s eta 0:08:00
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.3/38.5 MB 70.4 kB/s eta 0:08:49
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.6/38.5 MB 73.2 kB/s eta 0:08:25
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12
   - -------------------------------------- 1.8/38.5 MB 74.6 kB/s eta 0:08:12

In [2]:


import pandas as pd 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler,LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
file = r"C:\Users\KOIN\Downloads\apex.csv"

df = pd.read_csv(file)
df

,Loan_ID,Gender,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1002.0,1.0,0.0,0.0,1.0,0.0,5849.0,0.0,128.0,360.0,1.0,1.0,Y
1,1003.0,1.0,1.0,1.0,1.0,0.0,4583.0,1508.0,128.0,360.0,1.0,3.0,N
2,1005.0,1.0,1.0,0.0,1.0,1.0,3000.0,0.0,66.0,360.0,1.0,1.0,Y
3,1006.0,1.0,1.0,0.0,0.0,0.0,2583.0,2358.0,120.0,360.0,1.0,1.0,Y
4,1008.0,1.0,0.0,0.0,1.0,0.0,6000.0,0.0,141.0,360.0,1.0,1.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,2265.0,1.0,1.0,2.0,0.0,0.0,1993.0,1625.0,113.0,180.0,1.0,2.0,Y
407,2266.0,1.0,1.0,2.0,1.0,0.0,3100.0,1400.0,113.0,360.0,1.0,1.0,Y
408,2272.0,1.0,1.0,2.0,1.0,0.0,3276.0,484.0,135.0,360.0,0.0,2.0,Y
409,2277.0,2.0,0.0,0.0,1.0,0.0,3180.0,0.0,71.0,360.0,0.0,1.0,N
410,2281.0,1.0,1.0,0.0,1.0,0.0,3033.0,1459.0,95.0,360.0,1.0,1.0,Y

In [5]:
df.isnull().sum()
r = df["Loan_Status"].mode()[0]
df.fillna(r,inplace=True)
df.isnull().sum()

C:\Users\KOIN\AppData\Local\Temp\ipykernel_7976\4193542321.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Y' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna(r,inplace=True)

Loan_ID              0
Gender               0
Married              0
Dependents           0
Graduate             0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [6]:
df.fillna(df.mean(numeric_only=True) , inplace=True)

In [7]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Graduate             0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [8]:
x= df.drop(["Loan_Status"],axis=1)
y = df["Loan_Status"]

In [9]:
binary = ["Gender"]
numeric =['Married', 'Dependents', 'Graduate','Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount','Loan_Amount_Term', 'Credit_History', "Property_Area"]

In [10]:
prepro = ColumnTransformer(
    transformers = [
        ("cat",OneHotEncoder(drop="first"),binary)
        ,
        ("num" ,StandardScaler(),numeric)
    ]
)
prepro

ColumnTransformer(transformers=[('cat', OneHotEncoder(drop='first'),
                                 ['Gender']),
                                ('num', StandardScaler(),
                                 ['Married', 'Dependents', 'Graduate',
                                  'Self_Employed', 'ApplicantIncome',
                                  'CoapplicantIncome', 'LoanAmount',
                                  'Loan_Amount_Term', 'Credit_History',
                                  'Property_Area'])])

In [27]:
# model = Pipeline(steps=[
#     ("preprocessing ", prepro)
#     ,
#     ("classifire" , LogisticRegression)
    
# ])

In [17]:
y_train = y_train.astype(str)

In [18]:
model.fit(x_train,y_train)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['float', 'str']

In [16]:
x_train,x_test ,y_train ,y_test = train_test_split (x,y,test_size= 0.2,random_state=40)
model.fit(x_train,y_train)
y_pred  = model.predict(x_test)
acc = accuracy_score(y_pred,y_test)
acc

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['float', 'str']

In [14]:
model = Pipeline(steps=[
    ("preprocessing ", prepro)
    ,
    ("classifire" , LogisticRegression())
    
])
model

Pipeline(steps=[('preprocessing ',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['Gender']),
                                                 ('num', StandardScaler(),
                                                  ['Married', 'Dependents',
                                                   'Graduate', 'Self_Employed',
                                                   'ApplicantIncome',
                                                   'CoapplicantIncome',
                                                   'LoanAmount',
                                                   'Loan_Amount_Term',
                                                   'Credit_History',
                                                   'Property_Area'])])),
                ('classifire', LogisticRegression())])

In [21]:
model.fit(x_train,y_train)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['float', 'str']

In [13]:
y_pred = model.predict(x_test)

print("accuracy ", accuracy_score )
print("confusion" , confusion_matrix)

In [14]:
df.head(5)

,Loan_ID,Gender,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1002.0,1.0,0.0,0.0,1.0,0.0,5849.0,0.0,128.0,360.0,1.0,1.0,Y
1,1003.0,1.0,1.0,1.0,1.0,0.0,4583.0,1508.0,128.0,360.0,1.0,3.0,N
2,1005.0,1.0,1.0,0.0,1.0,1.0,3000.0,0.0,66.0,360.0,1.0,1.0,Y
3,1006.0,1.0,1.0,0.0,0.0,0.0,2583.0,2358.0,120.0,360.0,1.0,1.0,Y
4,1008.0,1.0,0.0,0.0,1.0,0.0,6000.0,0.0,141.0,360.0,1.0,1.0,Y

In [17]:
live = pd.DataFrame({
"Gender":[1.0],
"Married": [0.0],
"Dependents": [0.1],
"Graduate": [1.0],
"Self_Employed": [0.0],
"ApplicantIncome": [0.0],
"CoapplicantIncome":[2025.0],
"LoanAmount":[7600.0],
"Loan_Amount_Term":[360],
"Credit_History":[1.0],
"Property_Area":[2.0]

})

In [19]:
probability = model.predict_proba(live)

positive_proba = probability[0],[1]

label = "loan active " if  1>0.50 else "loan not active " 

print("loan result = ", label)

print("loan accuracy = ", positive_proba)