In [2]:
import numpy as np 
import pandas as pd

In [3]:
file_path = r"C:\Users\KOIN\Downloads\covid_toy.csv"
df= pd.read_csv(file_path )
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [5]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
df.fillna(df.mean(numeric_only= True), inplace=True)

In [8]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [9]:
x= df.drop("has_covid", axis=1)
y = df["has_covid"]

In [10]:
binary_cols =["gender", "fever","cough"]

nominal_cols= ["city"]

numeric_cols= ["age"]

In [11]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [12]:
preprocessor = ColumnTransformer(

    transformers =[
                   ("cat" , OneHotEncoder(drop="first") ,binary_cols + nominal_cols),

        ("num" , StandardScaler(),numeric_cols)
    ]
)

In [13]:

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression 

model= Pipeline(steps = [
    ("preprocesing", preprocessor),
    ("classifier", LogisticRegression())
])

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=43)

In [15]:
model.fit(X_train,y_train)

Pipeline(steps=[('preprocesing',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['gender', 'fever', 'cough',
                                                   'city']),
                                                 ('num', StandardScaler(),
                                                  ['age'])])),
                ('classifier', LogisticRegression())])

In [16]:
from sklearn.metrics import accuracy_score , confusion_matrix

y_pred = model.predict(X_test)

print("accoracy", accuracy_score(y_pred ,y_test))

print("confusion" , confusion_matrix(y_pred , y_test))

accoracy 0.55
confusion [[8 8]
 [1 3]]

In [17]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [28]:
live_input = pd.DataFrame({
    "age" : [20],
     "gender" : ["Male"],
     "fever" : [99],
     "cough" : ["Strong"],
     "city" : ["Delhi"]
})

In [31]:
probability = model.predict_proba(live_input)

positive_prob = probability[0],[1]

label = "covid positive " if 1> 0.50  else "covid nagative ";

print("result :" ,label)

print("accuracy result :" , positive_prob)

result : covid positive
accuracy result : (array([0.54805517, 0.45194483]), [1])